-- @table object_type;
-- @table access_type;
-- @table object;
-- @table tagging;
-- @table user_entity_type;
-- @table user_entity;
-- @table entity_access;
-- @table user_acount;
-- @table group_of_users;
-- @table entity_containing;
-- @table event;
-- @table event_in_calendar;
SELECT * FROM object_type;
SELECT * FROM access_type;
SELECT * FROM object;
SELECT * FROM tagging;
SELECT * FROM user_entity_type;
SELECT * FROM user_entity;
SELECT * FROM entity_access;
SELECT * FROM user_account;
SELECT * FROM group_of_users;
SELECT * FROM entity_containing;
SELECT * FROM event;
SELECT * FROM event_in_calendar;
